# docker-compose.yml
services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      APP_DEBUG: "true"   # quote to avoid YAML boolean conversion surprises
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
