# docker-compose.yml
services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      APP_DEBUG: "true"   # quote to avoid YAML boolean conversion surprises
      APP_ENABLE_TRACING: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      APP_DB_DSN: postgresql+asyncpg://rag:rag@db:5432/rag
      APP_REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - jaeger
      - redis

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  pgdata:
