name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]  # use 3.12 for widest tool support; 3.13 is fine if setup-python supports it
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tooling & deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .          # <— add this line
          pip install pytest ruff

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (ruff-format dry run)
        run: ruff format --check .

      - name: Type check (mypy)
        run: mypy src

      - name: Tests
        run: pytest
