name: ci

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE_NAME: ghcr.io/binodthapachhetry/ai-rag-agent

jobs:
  build-test:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tooling & deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest ruff mypy   # <-- add mypy here

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (ruff-format dry run)
        run: ruff format --check .

      - name: Type check (mypy)
        run: mypy src

      - name: Tests
        run: pytest -q

      # ---------- Build multi-arch image ----------

      # Enable CPU emulation for cross-arch builds
      - uses: docker/setup-qemu-action@v3

      # Set up Buildx builder
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & (conditionally) push multi-arch
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64                  # <-- multi-arch
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
